feat: add text to tool UI
MaffieLab/Coauthor pull request #47
Opened 2024-09-16 13:37 UTC by maffiemd

- User testing indicated confusion why the browser icon popup was blank

- Adds text to show the plugin is installed

- Adds troubleshooting URL and email

2024-09-21 22:32 UTC, leonzh2k requested changes

2024-09-21 22:32 UTC, leonzh2k commented on src/ui/ui.html
> +      The Coauthor Plugin is installed and ready to use.
Use `<br>` instead of `<br />`, both are equally valid HTML but the former takes less effort to write. See: https://stackoverflow.com/questions/1946426/html-5-is-it-br-br-or-br

2024-09-21 22:34 UTC, leonzh2k requested changes

2024-09-21 22:34 UTC, leonzh2k commented on src/ui/ui.html
> +      <br />
Use `<br>` instead of `<br />`, both are equally valid HTML but the former takes less effort to write. See: https://stackoverflow.com/questions/1946426/html-5-is-it-br-br-or-br

2024-09-22 13:20 UTC, maffiemd commented on src/ui/ui.html
> +      <br />
Prettier auto formats to a self closing tag instead of a void tag. From what I've found, this cannot be changed. 
https://github.com/prettier/prettier/issues/15336#issuecomment-1702961692

2024-09-22 18:49 UTC, leonzh2k approved these changes
Approved, make sure to merge using "squash and merge" since there's no value in having that code style commit be its own commit.

2024-09-22 18:49 UTC, leonzh2k commented on src/ui/ui.html
> +      <br />
Thanks for clarifying. In that case, this is fine.

2024-09-24 23:49 UTC, merged